[network]
listen_address = "/ip4/127.0.0.1/tcp/6884"
dial_peers = []
max_pending_incoming = 10
max_pending_outgoing = 10
max_established_incoming = 50
max_established_outgoing = 50
max_established_per_peer = 1
max_workbase_per_second = 10
max_userworkbase_per_second = 10
max_miningshare_per_second = 100
max_inventory_per_second = 100
max_transaction_per_second = 100
rate_limit_window_secs = 1
max_requests_per_second = 1
peer_inactivity_timeout_secs = 60
dial_timeout_secs = 30

[store]
path = "./store.db"
background_task_frequency_hours = 24
pplns_ttl_days = 7

[ckpool]
host = "localhost"
port = 8881

[stratum]
hostname = "0.0.0.0"
port = 3333
start_difficulty = 10000
minimum_difficulty = 100
solo_address = "tb1qyazxde6558qj6z3d9np5e6msmrspwpf6k0qggk"
# The bitcoin address to use for first jobs when there are no shares
bootstrap_address = "tb1qyazxde6558qj6z3d9np5e6msmrspwpf6k0qggk"
# Any donation amount for developers to be sent to donation address. Default no donation.
# donation_address = "tb1qyazxde6558qj6z3d9np5e6msmrspwpf6k0qggk"
# In basis points, 1% = 100 basis points. Default 0
# donation = 0
# Any fee amount for node/hydrapool provider to be sent to fee address. Default no fee.
# fee_address = "tb1qyazxde6558qj6z3d9np5e6msmrspwpf6k0qggk"
# In basis points, 1% = 100 basis points. Default 0
# fee = 0
zmqpubhashblock = "tcp://127.0.0.1:28332"
# The network can be "main", "testnet4" or "signet"
network = "signet"
version_mask = "1fffe000"
# The difficulty multiplier defines the window size for calculating payout proportions
# See https://github.com/p2poolv2/p2poolv2/wiki/Difficult-Multiplier on how to choose this
difficulty_multiplier = 1.0
handshake_timeout = 900
inactivity_timeout = 900
monitor_interval = 10

[miner]
pubkey = "020202020202020202020202020202020202020202020202020202020202020202"

[bitcoinrpc]
# RPC credentials are loaded from env vars
url = "http://127.0.0.1:38332"
username = "p2pool"
password = "p2pool"

[logging]
# Specify a file path for the log file, if no log file is specified, console logging will be used
# file = "./logs/p2pool.log"
level = "debug"
# Pool, user and worker stats are dumped for consumption by stats tools
stats_dir = "./logs/stats"

[api]
hostname = "127.0.0.1"
port = 46884
# Optional authentication credentials
# auth_user = "admin"
# auth_token is of the format salt:password-hmac. Use can p2poolv2_cli gen-auth to generate a token.
# auth_token = "your_secret_token"
